### ISSUE TITLE
插件还维护吗

### ISSUE THREAD

**Issue by chenjuyu** [rhymelph/r_scan#1]
能否加一个可以扫描条码的功能，还有可以打开 闪光灯的功能

**Comment by rhymelph** [comment]
当然，后续会添加

**Comment by doudoubaby** [comment]
pub.dev可以更新下么

**Comment by Eva-HYL** [comment]
请问有遇到过扫描页有个黑色的底，能扫描，但没有相机的那个页面的问题么？
![image](https://user-images.githubusercontent.com/20679225/70425792-c8931180-1aac-11ea-9a2a-ec11a38e404e.png)

**Comment by rhymelph** [comment]
闪光灯已添加，请更新到v0.1.1版本.相机默认支持条形码扫描

**Comment by chenjuyu** [comment]
期待大佬的持续更新，界面如果可以像微信扫一扫这样就更好了，现在的客户都挑剔，哎

**Comment by rhymelph** [comment]
界面可以自定义的@chenjuyu

**Comment by chenjuyu** [comment]
> 界面可以自定义的@chenjuyu

有具体的demo的吗？发来参考一下

**Comment by rhymelph** [comment]
参考：https://github.com/rhymelph/r_scan/blob/master/example/lib/scan_dialog.dart

**Comment by chenjuyu** [comment]
好的，我试一下，谢谢大佬
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:41
收件人:&nbsp;"rhymelph/r_scan"<r_scan@noreply.github.com&gt;;
抄送:&nbsp;"CHEN"<2498525982@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rhymelph/r_scan] 插件还维护吗 (#1)




参考：https://github.com/rhymelph/r_scan/blob/master/example/lib/scan_dialog.dart

**Comment by chenjuyu** [comment]
pubspec.yaml
r_scan: ^0.1.2 
运行这个版本，条码识别不了，扫描不了，还有一个问题就是扫描二维码成功后，多扫几次，会出现 闪退，大佬有遇到过吗 ？
环境 如下：
D:\my_app&gt;flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
&nbsp; &nbsp; • Flutter version 1.9.1+hotfix.6 at D:\flutter
&nbsp; &nbsp; • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
&nbsp; &nbsp; • Engine revision b863200c37
&nbsp; &nbsp; • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
&nbsp; &nbsp; • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
&nbsp; &nbsp; • Android NDK location not configured (optional; useful for native profiling support)
&nbsp; &nbsp; • Platform android-29, build-tools 29.0.2
&nbsp; &nbsp; • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
&nbsp; &nbsp; • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
&nbsp; &nbsp; ! Some Android licenses not accepted.&nbsp; To resolve this, run: flutter doctor --android-licenses


[√] Android Studio (version 3.5)
&nbsp; &nbsp; • Android Studio at C:\Program Files\Android\Android Studio
&nbsp; &nbsp; • Flutter plugin version 41.0.2
&nbsp; &nbsp; • Dart plugin version 191.8593
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)


[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
&nbsp; &nbsp; • IntelliJ at D:\IDEA20191
&nbsp; &nbsp; X Flutter plugin not installed; this adds Flutter specific functionality.
&nbsp; &nbsp; X Dart plugin not installed; this adds Dart specific functionality.
&nbsp; &nbsp; • For information about installing plugins, see
&nbsp; &nbsp; &nbsp; https://flutter.dev/intellij-setup/#installing-the-plugins


[√] Connected device (1 available)
&nbsp; &nbsp; • SQ51 • 42bb663e • android-arm • Android 5.1.1 (API 22)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:41
收件人:&nbsp;"rhymelph/r_scan"<r_scan@noreply.github.com&gt;;
抄送:&nbsp;"CHEN"<2498525982@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rhymelph/r_scan] 插件还维护吗 (#1)




参考：https://github.com/rhymelph/r_scan/blob/master/example/lib/scan_dialog.dart

**Comment by rhymelph** [comment]
请更新到最新版本的Flutter

**Comment by chenjuyu** [comment]
已经长级到 Flutter version 1.12.13+hotfix.5 at D:\flutter
怕个版本了，还是会闪退啊，不会是 android5.0 购建图片使用的是android.support，成新版本的androidx


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午5:54
收件人:&nbsp;"rhymelph/r_scan"<r_scan@noreply.github.com&gt;;
抄送:&nbsp;"CHEN"<2498525982@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rhymelph/r_scan] 插件还维护吗 (#1)




请更新到最新版本的Flutter

**Comment by rhymelph** [comment]
请粘贴错误信息
