### ISSUE TITLE
引入r_scan后，gradle编译不通过

### ISSUE THREAD

**Issue by qinrunhao** [rhymelph/r_scan#12]
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
G:\hope-git\r_scan-master\android\src\main\java\com\rhyme\r_scan\RScanPlugin.java:93: ����: �Ҳ�������
                flutterPluginBinding.getBinaryMessenger(),
                                    ^
  ����:   ���� getBinaryMessenger()
  λ��: ����ΪFlutterPluginBinding�ı�� flutterPluginBinding
G:\hope-git\r_scan-master\android\src\main\java\com\rhyme\r_scan\RScanPlugin.java:95: ����: �Ҳ�������
                flutterPluginBinding.getTextureRegistry(),
                                    ^
  ����:   ���� getTextureRegistry()
  λ��: ����ΪFlutterPluginBinding�ı�� flutterPluginBinding
G:\hope-git\r_scan-master\android\src\main\java\com\rhyme\r_scan\RScanPlugin.java:96: ����: �Ҳ�������
                flutterPluginBinding.getPlatformViewRegistry());
                                    ^
  ����:   ���� getPlatformViewRegistry()
  λ��: ����ΪFlutterPluginBinding�ı�� flutterPluginBinding
ע: G:\hope-git\r_scan-master\android\src\main\java\com\rhyme\r_scan\RScanCamera\RScanCamera.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
3 ������
[0x7FFC8309D3E0] ANOMALY: meaningless REX prefix used
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by rhymelph** [comment]
看看插件版本号

**Comment by qinrunhao** [comment]
最新的，直接在git上下载的源码，直接运行example。

**Comment by qinrunhao** [comment]
可能是AndroidX和support兼容引起的，请问这个插件哪个版本不是AndoridX的？谢谢。

**Comment by qinrunhao** [comment]
> 看看插件版本号

可能是AndroidX和support兼容引起的，请问这个插件哪个版本不是AndoridX的？谢谢。

**Comment by rhymelph** [comment]
目前example和插件都是AndroidX的

**Comment by qinrunhao** [comment]
我不是做安卓的，不太懂，所以问的不专业，请见谅！
为什么我仅仅运行下载的example也编译不通过呢？

**Comment by rhymelph** [comment]
编译不通过有可能是下载的依赖没下载完全，请自备翻墙

**Comment by qinrunhao** [comment]
排查后发现问题：RScanPlugin.java中成员变量FlutterPluginBinding来自包io.flutter.embedding.engine.FlutterEngine，该类中没有方法getBinaryMessenger()、getTextureRegistry()和getPlatformViewRegistry()，导致编译报错。io.flutter.embedding.engine.FlutterEngine包来自于android-arm64/flutter.jar，是否正确？

**Comment by rhymelph** [comment]
从上面看应该是你的Flutter版本过低
运行一下 flutter doctor -v

**Comment by rhymelph** [comment]
升级一下Flutter，没问题就关了

**Comment by qinrunhao** [comment]
正在升级，没问题后就关了

**Comment by qinrunhao** [comment]
的确是flutter版本的问题。非常感谢！
