### ISSUE TITLE
IOS上无法启用摄像头，显示：not have available camera

### ISSUE THREAD

**Issue by qinrunhao** [rhymelph/r_scan#16]
ios除了not have available camera外，图片扫描条码也是无任何数据返回，图片扫描二维码正常。

**Comment by rhymelph** [comment]
ios可以在获取可用的Camera之前先调用一下`permission_handler`包里的请求相机权限即可，图片扫条码的问题将再后续再慢慢改善，敬请期待

**Comment by qinrunhao** [comment]
> ios可以在获取可用的Camera之前先调用一下`permission_handler`包里的请求相机权限即可，图片扫条码的问题将再后续再慢慢改善，敬请期待

请求权限了，返回PermissionStatus.granted，但在后面获取摄像机列表依然为空。请问你的代码是怎么写的。
