### ISSUE TITLE
IOS下貌似有问题

### ISSUE THREAD

**Issue by sqw00453579** [rhymelph/r_scan#2]
IOS下貌似有问题，直接用example的代码编译没有报错，但是进入扫描二维码页面的时候只有个扫描框的动画而已，相机并没有被启动。期间也没有询问权限的提示，其中 Info.plist 已经设置了。
请教下是哪里没弄对吗？

flutter doctor 信息如下：
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/xxx
    • Framework revision cc949a8e8b (2 months ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio
    • Android Studio at /Users/xxx/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by rhymelph** [comment]
fix v0.1.1
