### ISSUE TITLE
UIWebView适配问题

### ISSUE THREAD

**Issue by xuzhenhao** [rhymelph/r_scan#21]
扫描时发现ZBarSDK含有UIWebview

./Pods/ZBarSDK/iphone/include/ZBarSDK/ZBarHelpController.h:                              < UIWebViewDelegate,
./Pods/ZBarSDK/iphone/include/ZBarSDK/ZBarHelpController.h:    UIWebView *webView;
./Pods/ZBarSDK/iphone/ZBarHelpController.m:    webView = [[UIWebView alloc]
./Pods/ZBarSDK/iphone/ZBarHelpController.m:- (void) webViewDidFinishLoad: (UIWebView*) view
./Pods/ZBarSDK/iphone/ZBarHelpController.m:- (BOOL)             webView: (UIWebView*) view
./Pods/ZBarSDK/iphone/ZBarHelpController.m:              navigationType: (UIWebViewNavigationType) nav

**Comment by masewo** [comment]
You can override the dependency used by r_scan by adding this to your podfile:

```
target 'Runner' do
  # temporary solution because official ZBarSDK did not switch from UIWebView to WKWebView yet
  pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35"

  ...
end
```

**Comment by rhymelph** [comment]
v0.1.6
