### ISSUE TITLE
TrustManager security vulnerability reported by Google Play

### ISSUE THREAD

**Issue by AkoWu101** [rhymelph/r_scan#32]
Can help to fix this issue?

**Comment by SurajLad** [comment]
@KingWu Facing the same issue in my app Did you got any luck yet?

**Comment by AkoWu101** [comment]
@SurajLad for ios, i use `0.1.3+2` to build. 

for android, i switch to use this branch

```
r_scan:
    git:
      url: git://github.com/ARRO-Coffee/r_scan.git
```

**Comment by Dhuliang** [comment]
Same problem.

**Comment by SurajLad** [comment]
> /github.com/ARRO-Coffee/r_scan.git

@KingWu Thanks

**Comment by rhymelph** [comment]
0.1.5 version
