### ISSUE TITLE
最新版构建iOS失败，以下是报错内容

### ISSUE THREAD

**Issue by McPorkChop** [rhymelph/r_scan#35]
‘’‘
    5 warnings generated.
    781 warnings and 3 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'FMDB' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'Toast' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'Reachability' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'audioplayers' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'shared_preferences' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'webview_flutter' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'wakelock' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'video_player' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'url_launcher' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'sensors' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'screen' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'permission_handler' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'path_provider' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'image_picker' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'foundation_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'fluwx_worker' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'flutter_custom_dialog' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'flutter_adapter' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'e2e' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'core_location_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'ZBarSDK' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'Protobuf' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'ZXingObjC' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'fluttertoast' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'connectivity' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'amap_core_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'r_scan' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'flutter_blue' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'amap_map_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'amap_search_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'amap_location_fluttify' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'AMapLocation' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'AMap3DMap' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'AMapSearch' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'Flutter' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'AMapFoundation' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 mini.
’‘’

**Comment by qweqwqsqwwew** [comment]
擦，我也是

**Comment by qweqwqsqwwew** [comment]
flutter升级的最新版本 编译就会报错
看老哥两天前还有更新提交，目测没凉

**Comment by rhymelph** [comment]
File - > Workspace Settings ->  Build System : New Build System

**Comment by McPorkChop** [comment]
> File - > Workspace Settings -> Build System : New Build System

didnt find any Workspace settings in vscode or idea

**Comment by rhymelph** [comment]
@McPorkChop  xcode

**Comment by McPorkChop** [comment]
> @McPorkChop xcode

并不能解决通过命令行打包的报错问题

**Comment by rhymelph** [comment]
没有看到 error 的信息

**Comment by qweqwqsqwwew** [comment]
已经解决了，改个头文件路径就行

**Comment by qweqwqsqwwew** [comment]
> > @McPorkChop xcode
> 
> 并不能解决通过命令行打包的报错问题

你先xcode编译，报错的地方是头文件路径引用，你改下就行

**Comment by McPorkChop** [comment]
> 没有看到 error 的信息

/Users/alfredmcporkchop/Documents/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/r_scan-0.1.5/ios/Classes/RScanResult.h:10:9: Include of non-modular header inside framework module 'r_scan.RScanResult': '/Users/alfredmcporkchop/Library/Developer/Xcode/DerivedData/Runner-cupmrqzhxhfirldzzzqatynypcdk/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/ZXingObjC/ZXingObjC.framework/Headers/ZXingObjC.h'

**Comment by McPorkChop** [comment]
> > > @McPorkChop xcode
> > 
> > 
> > 并不能解决通过命令行打包的报错问题
> 
> 你先xcode编译，报错的地方是头文件路径引用，你改下就行

改成啥？我不了解iOS

**Comment by qweqwqsqwwew** [comment]
![image](https://user-images.githubusercontent.com/19162597/100821752-f9254580-348b-11eb-9dba-b978cd4d4873.png)
改个头文件路径

**Comment by qweqwqsqwwew** [comment]
> > > > @McPorkChop xcode
> > > 
> > > 
> > > 并不能解决通过命令行打包的报错问题
> > 
> > 
> > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> 
> 改成啥？我不了解iOS

看下

**Comment by McPorkChop** [comment]
还发现一个问题，在iOS版本当中引用了UIWebView，被苹果审核拒绝

**Comment by McPorkChop** [comment]
> > > > > @McPorkChop xcode
> > > > 
> > > > 
> > > > 并不能解决通过命令行打包的报错问题
> > > 
> > > 
> > > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> > 
> > 
> > 改成啥？我不了解iOS
> 
> 看下

谢谢，但是发现无法提审，第三方库过老。

**Comment by qweqwqsqwwew** [comment]
> > > > > > @McPorkChop xcode
> > > > > 
> > > > > 
> > > > > 并不能解决通过命令行打包的报错问题
> > > > 
> > > > 
> > > > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> > > 
> > > 
> > > 改成啥？我不了解iOS
> > 
> > 
> > 看下
> 
> 谢谢，但是发现无法提审，第三方库过老。

  pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35" 
大兄弟，只能帮你到这儿了

**Comment by qweqwqsqwwew** [comment]
作者最好出个新版本，处理一下

**Comment by michaelPual** [comment]
> > > > > > > @McPorkChop xcode
> > > > > > 
> > > > > > 
> > > > > > 并不能解决通过命令行打包的报错问题
> > > > > 
> > > > > 
> > > > > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> > > > 
> > > > 
> > > > 改成啥？我不了解iOS
> > > 
> > > 
> > > 看下
> > 
> > 
> > 谢谢，但是发现无法提审，第三方库过老。
> 
> pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35"
> 大兄弟，只能帮你到这儿了

这是什么意思？

**Comment by qweqwqsqwwew** [comment]
> > > > > > > > @McPorkChop xcode
> > > > > > > 
> > > > > > > 
> > > > > > > 并不能解决通过命令行打包的报错问题
> > > > > > 
> > > > > > 
> > > > > > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> > > > > 
> > > > > 
> > > > > 改成啥？我不了解iOS
> > > > 
> > > > 
> > > > 看下
> > > 
> > > 
> > > 谢谢，但是发现无法提审，第三方库过老。
> > 
> > 
> > pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35"
> > 大兄弟，只能帮你到这儿了
> 
> 这是什么意思？

放podfile ，终端pod install

**Comment by lvsecoto** [comment]
> 作者最好出个新版本，处理一下

可以Fork这个项目git仓库，自己修改一下，上传。然后依赖git仓库

**Comment by michaelPual** [comment]
> > > > > > > > > @McPorkChop xcode
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 并不能解决通过命令行打包的报错问题
> > > > > > > 
> > > > > > > 
> > > > > > > 你先xcode编译，报错的地方是头文件路径引用，你改下就行
> > > > > > 
> > > > > > 
> > > > > > 改成啥？我不了解iOS
> > > > > 
> > > > > 
> > > > > 看下
> > > > 
> > > > 
> > > > 谢谢，但是发现无法提审，第三方库过老。
> > > 
> > > 
> > > pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35"
> > > 大兄弟，只能帮你到这儿了
> > 
> > 
> > 这是什么意思？
> 
> 放podfile ，终端pod install

好的，谢谢

**Comment by rhymelph** [comment]
v0.1.6
