### ISSUE TITLE
Does not run on ios

### ISSUE THREAD

**Issue by xande-er** [rhymelph/r_scan#36]
Everything used to work very well, but when the new version came out, it stopped running and building
"""
#import <r_scan/RScanPlugin.h>

"""
Could not build module 'r_scan'
/Users/ol/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/r_scan-0.1.5/ios/Classes/RScanResult.h:10:9: Include of non-modular header inside framework module 'r_scan.RScanResult': '/Users/ol/Library/Developer/Xcode/DerivedData/Runner-fbufjpmrzasmmdasmlpibasaxzjs/Build/Products/Debug-iphonesimulator/ZXingObjC/ZXingObjC.framework/Headers/ZXingObjC.h'

Also when creating a new project, and adding to the pubspec.yaml of this package, there is the same error, opposed to 2 pc

**Comment by rhymelph** [comment]
v0.1.6
