### ISSUE TITLE
如何实现连续的两个页面实现扫码

### ISSUE THREAD

**Issue by butterflyXX** [rhymelph/r_scan#37]
我们项目要实现扫商品码,然后再扫用户二维码支付,涉及到两个页面要使用扫码功能,而且扫用户二维码的时候手动返回可以继续扫商品码,这种要如何实现啊,请求指导

**Comment by butterflyXX** [comment]
实现了,
在scanA中重新初始化controller即可

**Comment by rhymelph** [comment]
close
