### ISSUE TITLE
[!] Error installing ZXingObjC

### ISSUE THREAD

**Issue by shanyuepeng** [rhymelph/r_scan#43]
[!] Error installing ZXingObjC
    [!] /usr/bin/git clone https://github.com/zxingify/zxingify-objc.git
    /var/folders/rs/l6kmmwhs7hdf1qw0m86cjtwm0000gn/T/d20210108-25388-zjkkru --template= --single-branch --depth 1 --branch
    3.6.5

**Comment by rhymelph** [comment]
v0.1.6
