### ISSUE TITLE
Poor quality preview

### ISSUE THREAD

**Issue by ghost** [rhymelph/r_scan#7]
Preview quality is poor in full screen. How can I fix it? And is there a way to set scan area?

FlutterRScanView: DisplayMetrics{density=1.75, width=720, height=1436, scaledDensity=1.75, xdpi=280.0, ydpi=280.0}

![Screenshot_20200121-173107](https://user-images.githubusercontent.com/45110123/72813385-459cd380-3c74-11ea-9ef3-e097a3cd9a18.jpg)

**Comment by rhymelph** [comment]
upgraded to  v0.1.4 version，add the base on Texture widget in RScanCamera，👏👏welcome to use it
